"""
AnnaBet League ID Mapping
Maps league names to AnnaBet's serie_ID (used in URLs like
annabet.com/en/soccerstats/serie_{ID}_{Name}.html).

Built from AnnaBet's own country/league directory. Scope matches the
original SoccerStats LEAGUE_CODES — domestic top-flight and second
divisions, skipping cups/super cups/youth/friendlies to keep this
comparable and relevant to the prediction model.
"""

ANNABET_LEAGUE_IDS = {
    "England - Premier League": 1,
    "England - Championship": 2,
    "England - League One": 13,
    "England - League Two": 14,
    "England - National League": 15,
    "England - National League North": 143,
    "England - National League South": 144,
    "England - Isthmian League": 268,
    "England - Northern Premier League": 267,
    "England - Southern Football League": 263,
    "Italy - Serie A": 3,
    "Italy - Serie B": 19,
    "Italy - Serie C": 817,
    "Italy - Serie C Group A": 137,
    "Italy - Serie C Group B": 138,
    "Italy - Serie C Group C": 623,
    "Spain - LaLiga": 4,
    "Spain - Segunda Division": 39,
    "Germany - Bundesliga": 8,
    "Germany - 2. Bundesliga": 56,
    "Germany - 3. Liga": 145,
    "France - Ligue 1": 5,
    "France - Ligue 2": 49,
    "France - Championnat National": 154,
    "Netherlands - Eredivisie": 28,
    "Netherlands - Eerste Divisie": 229,
    "Netherlands - Tweede Divisie": 696,
    "Belgium - Pro League": 55,
    "Belgium - First Amateur Division": 697,
    "Portugal - Primeira Liga": 25,
    "Portugal - Liga Portugal 2": 204,
    "Scotland - Premiership": 20,
    "Scotland - Championship": 37,
    "Scotland - League One": 156,
    "Scotland - League Two": 157,
    "Russia - Premier League": 54,
    "Russia - First League": 164,
    "Albania - Superliga": 231,
    "Algeria - Ligue 1": 257,
    "Argentina - Primera Division": 212,
    "Armenia - Premier League": 351,
    "Australia - A-League": 148,
    "Australia - Brisbane Premier League": 465,
    "Austria - Bundesliga": 112,
    "Austria - 2. Liga": 168,
    "Azerbaijan - Premier League": 343,
    "Bahrain - Premier League": 458,
    "Belarus - Premier League": 232,
    "Bolivia - LFPB": 400,
    "Bosnia - Premier League": 216,
    "Brazil - Serie A": 217,
    "Brazil - Serie B": 259,
    "Bulgaria - A PFG": 218,
    "Bulgaria - Second League": 508,
    "Canada - Premier League": 750,
    "Chile - Primera Division": 301,
    "Chile - Primera B": 669,
    "China - Super League": 248,
    "China - League One": 731,
    "Colombia - Primera A": 329,
    "Colombia - Primera B": 554,
    "Costa Rica - Primera Division": 350,
    "Croatia - 1. HNL": 171,
    "Cyprus - First Division": 234,
    "Czech Republic - 1. Liga": 59,
    "Czech Republic - 2. Liga": 219,
    "Denmark - Superligaen": 38,
    "Denmark - 1st Division": 46,
    "Ecuador - Serie A": 313,
    "Egypt - Premier League": 450,
    "El Salvador - Primera Division": 293,
    "Estonia - Meistriliiga": 242,
    "Estonia - Esiliiga": 647,
    "Faroe Islands - Premier League": 368,
    "Finland - Veikkausliiga": 7,
    "Finland - Ykkosliiga": 35,
    "Georgia - Erovnuli Liga": 235,
    "Greece - Super League": 27,
    "Greece - Football League": 258,
    "Greece - Super League 2": 769,
    "Guatemala - Liga Nacional": 333,
    "Honduras - Liga Nacional": 553,
    "Hong Kong - Premier League": 442,
    "Hungary - NB I": 233,
    "Hungary - NB II": 517,
    "Iceland - Urvalsdeild": 114,
    "Iceland - Division 1": 392,
    "Iceland - Division 2": 688,
    "India - I-League": 276,
    "India - Super League": 676,
    "Indonesia - Liga 1": 327,
    "Iran - Pro League": 310,
    "Iran - Azadegan League": 513,
    "Iraq - Premier League": 478,
    "Israel - Premier League": 262,
    "Israel - Liga Leumit": 299,
    "Jamaica - National Premier League": 628,
    "Japan - J. League": 44,
    "Japan - J. League 2": 166,
    "Jordan - League": 445,
    "Kazakhstan - Premier League": 328,
    "Kenya - Premier League": 663,
    "Kuwait - Premier League": 349,
    "Latvia - Virsliga": 223,
    "Lithuania - A Lyga": 226,
    "Luxembourg - BGL Ligue": 322,
    "Malaysia - Super League": 521,
    "Malta - Premier League": 335,
    "Mexico - Liga MX": 334,
    "Mexico - Liga de Ascenso": 438,
    "Moldova - National Division": 424,
    "Montenegro - First League": 415,
    "Morocco - Botola": 330,
    "New Zealand - Championship": 454,
    "Nicaragua - Liga Primera": 760,
    "North Macedonia - 1. MFL": 250,
    "Northern Ireland - IFA Premiership": 280,
    "Norway - Eliteserien": 36,
    "Norway - 1st Division": 173,
    "Paraguay - Primera Division": 347,
    "Peru - Primera Division": 321,
    "Poland - Ekstraklasa": 10,
    "Poland - I liga": 104,
    "Qatar - Stars League": 515,
    "Republic of Ireland - Premier Division": 42,
    "Republic of Ireland - First Division": 163,
    "Romania - Liga I": 6,
    "Romania - Liga II": 270,
    "San Marino - League": 507,
    "Saudi Arabia - Professional League": 444,
    "Serbia - SuperLiga": 275,
    "Serbia - First League": 432,
    "Singapore - S.League": 213,
    "Slovakia - Superliga": 60,
    "Slovakia - 2. Liga": 120,
    "Slovenia - PrvaLiga": 149,
    "South Africa - Premier Soccer League": 260,
    "South Korea - K League 1": 249,
    "South Korea - K League 2": 543,
    "Sweden - Allsvenskan": 32,
    "Sweden - Superettan": 33,
    "Switzerland - Super League": 113,
    "Switzerland - Challenge League": 220,
    "Syria - Premier League": 300,
    "Taiwan - Premier League": 763,
    "Tajikistan - Higher League": 761,
    "Tanzania - Premier League": 732,
    "Thailand - League 1": 356,
    "Tunisia - Ligue 1": 469,
    "Turkey - Super Lig": 26,
    "Turkey - TFF First League": 209,
    "Turkmenistan - Higher League": 764,
    "UAE - Football League": 316,
    "Uganda - Super League": 643,
    "Ukraine - Premier League": 53,
    "Ukraine - 1. League": 423,
    "Uruguay - Primera Division": 439,
    "USA - MLS": 43,
    "USA - USL Championship": 362,
    "Venezuela - Primera Division": 314,
    "Vietnam - V.League 1": 426,
    "Wales - Premier League": 261,
}
